<?php
/**
 * Copyright © 2021 Codazon. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$recentPhotos = $block->getStoredInstagramPhotos();
$maxCount = 8;
$helper = $this->helper(\Codazon\ThemeLayoutPro\Helper\Data::class);
?>
<?php if( count($recentPhotos) > 0 ): ?>
<?php $i = 0; foreach($recentPhotos as $photo): ?>
<?php
    $img = $photo->images->thumbnail;
?>
<div class="item photo-item">
    <a class="photo-item-link abs-img" style="padding-bottom: 100%" href="<?php echo $photo->link ?>" target="_blank">
        <img alt="" class="img-responsive cdz-lazy" src="<?= $helper->getMediaUrl($img->url) ?>" />
    </a>
</div>
<?php $i++; if ($i == $maxCount) break ?>
<?php endforeach ?>
<?php endif ?>