<?php
/**
 * Copyright © 2021 Codazon. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
$recentPhotos = $block->getStoredInstagramPhotos();
$widget = ['themewidgets' => [
	'codazon.slider' => ['sliderConfig' => $block->getSliderData()]
]];
$rows = $this->getData('total_rows')?:1;
$maxI = $this->getData('max_items') - 1;
$count = count($recentPhotos);
$sliderMargin = (float)$this->getData('slider_margin');
$helper = $this->helper(\Codazon\ThemeLayoutPro\Helper\Data::class);
?>
<?php if ($count > 0 ) : ?>
<div class="instagram-photos items owl-carousel" data-mage-init='<?= json_encode($widget) ?>'>
	<?php $i = 0; foreach($recentPhotos as $photo): ?>
    <?php echo (($i%$rows == 0) && ($rows > 1))?'<div class="item-group">':'' ?>
    <div class="photo-item" <?php echo ($rows > 1)?"style='margin-bottom: {$sliderMargin}px'":'' ?>>
        <a class="photo-item-link abs-img" style="padding-bottom: 100%" href="<?php echo $photo->link ?>" target="_blank">
            <img alt="" class="img-responsive" src="<?= $helper->getMediaUrl($photo->images->standard_resolution->url); ?>" />
        </a>
    </div>
    <?php echo ((($i%$rows == $rows - 1) || ($i == ($count - 1)) || ($i == $maxI)) && ($rows > 1))?'</div>':'' ?>
    <?php if ($i == $maxI) break; ?>
    <?php $i++ ?>
    <?php endforeach ?>
</div>
<?php endif ?>